import React from 'react';
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';

// Define styles for a clean, legal look
const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: 'Helvetica' },
  header: { fontSize: 18, marginBottom: 20, textAlign: 'center', fontWeight: 'bold' },
  section: { marginBottom: 15 },
  label: { fontSize: 10, color: '#666', marginBottom: 2 },
  value: { fontSize: 12, marginBottom: 10 },
  bold: { fontWeight: 'bold' },
  signatureBlock: { marginTop: 50, borderTopWidth: 1, borderColor: '#000', paddingTop: 10, width: '60%' },
  disclaimer: { position: 'absolute', bottom: 30, left: 40, right: 40, fontSize: 8, color: '#999', textAlign: 'center' }
});

interface LODProps {
  user: {
    legalName: string; // "Tommy McDermott"
    artistName: string; // "TomEE"
    address: string;   // Full mailing address
    ipiNumber?: string;
  };
  adminCompany: {
    name: string;      // "Paperwork Administration, LLC"
    address: string;
  };
  date: string;
}

export const LetterOfDirectionPDF = ({ user, adminCompany, date }: LODProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      
      {/* HEADER */}
      <Text style={styles.header}>LETTER OF DIRECTION</Text>

      {/* RECIPIENT (Generic to all societies) */}
      <View style={styles.section}>
        <Text>TO: The Mechanical Licensing Collective (The MLC)</Text>
        <Text>TO: ASCAP / BMI / SESAC / GMR</Text>
        <Text>TO: SoundExchange</Text>
        <Text>TO: All Other Collection Societies and Income Sources</Text>
      </View>

      <View style={styles.section}>
        <Text>Date: {date}</Text>
      </View>

      {/* BODY */}
      <View style={styles.section}>
        <Text>Re: Administration of Musical Compositions for: <Text style={styles.bold}>{user.artistName}</Text></Text>
      </View>

      <View style={styles.section}>
        <Text style={{ marginBottom: 10 }}>To Whom It May Concern:</Text>
        
        <Text style={{ marginBottom: 10, lineHeight: 1.5 }}>
          Please be advised that I, <Text style={styles.bold}>{user.legalName}</Text> (p/k/a "{user.artistName}"), 
          have entered into an exclusive administration agreement with <Text style={styles.bold}>{adminCompany.name}</Text> ("Administrator") 
          for the world, effective as of {date}.
        </Text>

        <Text style={{ marginBottom: 10, lineHeight: 1.5 }}>
          Accordingly, please accept this letter as my irrevocable authorization and direction to:
        </Text>

        <Text style={{ marginLeft: 20, marginBottom: 5 }}>1. Update your records to reflect {adminCompany.name} as the administrator for all musical compositions owned or controlled by me.</Text>
        <Text style={{ marginLeft: 20, marginBottom: 5 }}>2. Direct all future statements and royalty payments (including any retroactive "black box" or suspense monies currently held) directly to Administrator at the address below.</Text>
        <Text style={{ marginLeft: 20, marginBottom: 5 }}>3. Grant Administrator full online access to my accounts and catalog data for the purpose of registration and maintenance.</Text>
      </View>

      {/* ADMIN INFO */}
      <View style={{ ...styles.section, marginTop: 20, padding: 10, backgroundColor: '#f0f0f0' }}>
        <Text style={styles.bold}>ALL PAYMENTS AND CORRESPONDENCE SHOULD BE SENT TO:</Text>
        <Text>{adminCompany.name}</Text>
        <Text>{adminCompany.address}</Text>
      </View>

      {/* SIGNATURE */}
      <View style={styles.signatureBlock}>
        {/* We can insert a digital signature image here if we have it */}
        <Text style={styles.bold}>Signed: __________________________</Text>
        <Text>{user.legalName}</Text>
        <Text>IPI: {user.ipiNumber || 'N/A'}</Text>
        <Text>Date: {date}</Text>
      </View>

      <Text style={styles.disclaimer}>
        Generated by Paperwork System | Doc Ref: {date.replace(/-/g,'')}-{user.artistName.replace(/\s/g,'').toUpperCase()}
      </Text>

    </Page>
  </Document>
);