// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: 'postgresql://postgres:p4p3rw0rk_r0y4lt13s@db.mesotcjxelhyjhnobfvl.supabase.co:5432/postgres',
  },
});
